poll_rate = 100
play_res = '1920x1080+1920,0'
alt_res = ['330x1000+2715,40', '1920x300+1920,390', '320x16384+2720,-7652']

[hooks]
reset = ''
alt_res = ['sh /home/pramodhsathya/MCSR/thin.sh', 'sh /home/pramodhsathya/MCSR/wide.sh', 'sh /home/pramodhsathya/MCSR/tall.sh']
normal_res = ['sh /home/pramodhsathya/MCSR/reset.sh', 'sh /home/pramodhsathya/MCSR/reset.sh', 'sh /home/pramodhsathya/MCSR/tall_reset.sh']
focus_gained = "python3 /home/pramodhsathya/MCSR/Rebinder.py focus"
focus_lost = "python3 /home/pramodhsathya/MCSR/Rebinder.py unfocus"

[keybinds]
Z = ['ingame_reset']
Ctrl-Shift-F = ['ingame_focus']
grave= ['ingame_toggle_res']
# m4alt = ['ingame_toggle_res']
6 = ['ingame_toggle_res(2)']
J = ['ingame_toggle_res(3)']
